In [353]:
import pandas as pd
import numpy as np
import re

In [354]:
#pip install xlrd

In [355]:
#Download the file
df = pd.read_excel("GSAF5.xls")
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,...,Unknown,Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,...,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,...,Unknown,Andy Currie: Province Sud:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,...,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,...,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [356]:
#Eliminar columnas por nombre 
columns_to_drop = { 
    'pdf',
    'href',
    'href formula',
    'Case Number',
    'Case Number.1',
    'original order',
    'Unnamed: 21',
    'Unnamed: 22'
}
df = df.drop(columns=columns_to_drop)

In [357]:
df.shape

(7065, 15)

In [358]:
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,10th January,2026.0,Unprovoked,Australia,NSW,Avalon Beach,Surfing,Paul Stanton,M,?,puncture mark to left thumb,N,0540hrs,Unknown,Bob Myatt GSAF
1,8th January,2026.0,Unprovoked,US Virgin Islands,Fredricksted Island St Croix,Dorsch Beach,Snorkeling,Arlene Lillis,F,56,Left arm torn off in the attack below the elbow,Y,1628hrs,Unknown,Todd Smith: KevinMcMurray Trackingsharks.com
2,3rd January,2026.0,Unprovoked,New Caledonia,Kélé,Between Bourail and Moindou,Scuba Diving,Unknown,M,?,Injuries to upper limbs,N,?,Unknown,Andy Currie: Province Sud:
3,21st December,2025.0,Unprovoked,USA,California,Lovers Point Pacific Grove,Swimming,Erica Fox,F,55,Taken by shark body recovered with multiple in...,Y,1200hrs,Great White Shark,Kevin McMurray Tracking sharks.com: Ralph Coll...
4,12th December,2025.0,Unprovoked,USA,Sonoma County California,Salmon Creek,Surfing,Unknown,M,?,Hand Injury,N,0800hrs,Suspected Great White Shark,Kevin McMurray Tracking sharks.com:Andrew Curr...

#### ver los valores nulos y duplicados

In [359]:
df.isna().sum()/df.shape[0]

Date         0.000000
Year         0.000283
Type         0.002548
Country      0.007077
State        0.068931
Location     0.080255
Activity     0.082803
Name         0.030998
Sex          0.081953
Age          0.423921
Injury       0.004954
Fatal Y/N    0.079406
Time         0.499222
Species      0.443171
Source       0.002831
dtype: float64

In [360]:
df.duplicated().sum()

1

In [361]:
filas_duplicadas = df[df.duplicated(keep=False)]
filas_duplicadas

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
5436,Fall 1943,1943.0,Unprovoked,USA,Hawaii,"Midway Island, Northwestern Hawaiian Islands",Spearfishing,2 males,M,NaN,Calf nipped in each case,N,NaN,"""small sharks""",W. M. Chapman
5437,Fall 1943,1943.0,Unprovoked,USA,Hawaii,"Midway Island, Northwestern Hawaiian Islands",Spearfishing,2 males,M,NaN,Calf nipped in each case,N,NaN,"""small sharks""",W. M. Chapman

In [362]:
#eliminando duplicados 
df = df.drop(5436)

In [363]:
df.shape

(7064, 15)

### Column Type

In [303]:
#Looks Type 
df['Type'].unique()

array(['Unprovoked', 'Provoked', 'Questionable', 'unprovoked',
       ' Provoked', 'Watercraft', 'Sea Disaster', nan, '?', 'Unconfirmed',
       'Unverified', 'Invalid', 'Under investigation', 'Boat'],
      dtype=object)

In [173]:
#Clean type
df['Type'] = df['Type'].astype(str).str.strip().str.capitalize()

#Unificar valores raros a 'Unkown
df['Type'] = df['Type'].replace({
    'Unverified': 'Unknown',
    'Unconfirmed': 'Unknown',
    '?': 'Unknown',
    'Nan': 'Unknown',         
    'Invalid': 'Unknown',
    'Under investigation': 'Unknown',
    'Questionable' : 'Unknown'
})

#unificar 'Unprovoked' y 'Provoked' (ya los capitalizamos)
df['Type'] = df['Type'].replace({'Unprovoked': 'Unprovoked', 'Provoked': 'Provoked'})

#otros tipos 
df['Type'] = df['Type'].replace({'Watercraft': 'Other', 'Sea disaster': 'Other', 'Boat': 'Other'})

In [174]:
#Los cambios se hicieron efectivos 
df['Type'].unique()

array(['Unprovoked', 'Provoked', 'Unknown', 'Other'], dtype=object)

### Hipotesis 2: Mueren mas hombres que mujeres?

In [175]:
df['Sex'].unique()

array(['M', 'F', 'F ', 'M ', nan, ' M', 'm', 'lli', 'M x 2', 'N', '.'],
      dtype=object)

#### Eliminacion de Nulos de ['Sex']

In [176]:
#Revisando los nulos de la columna 'Sex'
df['Sex'].isnull().sum()

579

In [177]:
#Quitamos espacios en blanco y ponemos todos en mayuscula, para unificar valores
df['Sex'] = df['Sex'].str.strip().str.upper()
df['Sex'].unique()

array(['M', 'F', nan, 'LLI', 'M X 2', 'N', '.'], dtype=object)

In [80]:
#Englobamos valores raros a 'Unkown'
df['Sex'] = df['Sex'].replace({
    'M X 2': 'Unknown',
    'LLI': 'Unknown',
    'N': 'Unknown',
    '.': 'Unknown'       
})

df['Sex'].unique()

array(['M', 'F', nan, 'Unknown'], dtype=object)

In [81]:
df['Sex'].isna().sum()

579

In [82]:
#Eliminacion de 'nan' de nuestra columna Sex
df = df.dropna(subset=['Sex'])

In [83]:
#Verificamos que se eliminaron los 'nan'
df['Sex'].unique()

array(['M', 'F', 'Unknown'], dtype=object)

In [84]:
#Utilizamos describe para ver cuando es el valor mas frecuente en Sex que es hombre
df['Sex'].describe()

count     6485
unique       3
top          M
freq      5670
Name: Sex, dtype: object

#### Hipotesis 2: En que año hay mas ataques

In [85]:
df['Year'].unique()

array([2026., 2025., 2024., 2023., 2022., 2021., 2020., 2019., 2018.,
       2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
       2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
       2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994., 1993.,
       1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986., 1985.,
       1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976., 1975.,
       1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966., 1965.,
       1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957., 1956.,
       1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948., 1848.,
       1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939.,
       1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931., 1930.,
       1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922., 1921.,
       1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913., 1912.,
       1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904., 1903.,
       1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895., 1894.,
       1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886., 1885.,
       1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877., 1876.,
       1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868., 1867.,
       1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859., 1858.,
       1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849., 1847.,
       1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837., 1835.,
       1834., 1832., 1831., 1830., 1829., 1828., 1827., 1826., 1825.,
       1819., 1818., 1817., 1816., 1815., 1812., 1811., 1810., 1808.,
       1807., 1805., 1803., 1801., 1800., 1792., 1791., 1787., 1786.,
       1785., 1784., 1783., 1780., 1779., 1776., 1771., 1767., 1764.,
       1758., 1753., 1751., 1749., 1755., 1748., 1742., 1738., 1723.,
       1721., 1703., 1700., 1642., 1691., 1640., 1638., 1595., 1580.,
       1555., 1554., 1543., 1518., 1500., 1000.,   77.,    5.,    0.])

In [86]:
#Haciendo analisis de los datos de Year y quedandonos con los años mayor a 1000
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df.loc[df['Year'] <= 1000, 'Year'] = np.nan

print("NaN:", df['Year'].isna().sum())
print("Filas antes:", df.shape[0])

NaN: 126
Filas antes: 6485

In [87]:
#Eliminando los valor "nan"
df = df.dropna(subset=['Year'])
print("Filas después:", df.shape[0])

Filas después: 6359

In [88]:
moda_year = df['Year'].mode()[0]
moda_year

2015.0

### Columna Fatal y/n

In [89]:
df['Fatal Y/N'].unique()

array(['N', 'Y', 'F', 'M', nan, 'n', 'Nq', 'UNKNOWN', 2017, 'Y x 2', ' N',
       'y'], dtype=object)

In [90]:
#Quitamos espacios en blanco y ponemos todos en mayuscula, para unificar valores
df['Fatal Y/N'] = df['Fatal Y/N'].str.strip().str.upper()
df['Fatal Y/N'].unique()

array(['N', 'Y', 'F', 'M', nan, 'NQ', 'UNKNOWN', 'Y X 2'], dtype=object)

In [91]:
#Englobamos valores raros a 'Unkown'
df['Fatal Y/N'] = df['Fatal Y/N'].replace({
    'Y X 2': 'Y',
    'NQ': 'N'          
})

df['Fatal Y/N'].unique()

array(['N', 'Y', 'F', 'M', nan, 'UNKNOWN'], dtype=object)

In [92]:
#Convirtiendo "UNKNOWN", "F", "M", en nan
# todo lo que NO sea Y o N pasalo a np.nan
df.loc[~df['Fatal Y/N'].isin(['Y', 'N']), 'Fatal Y/N'] = np.nan

df['Fatal Y/N'].value_counts(dropna=False)

Fatal Y/N
N      4511
Y      1323
NaN     525
Name: count, dtype: int64

In [93]:
#eliminamos los nan 
df = df.dropna(subset=['Fatal Y/N'])

In [94]:
#Visualizando cambios y utilizando describe para observar cuales son los mas frequentes 
print(df['Fatal Y/N'].unique())

df['Fatal Y/N'].describe()

['N' 'Y']

count     5834
unique       2
top          N
freq      4511
Name: Fatal Y/N, dtype: object

In [95]:
#Observando el porcentaje con respecto a la muestra final con la que nos quedamos 
(df['Fatal Y/N'].value_counts(normalize=True)['N']) * 100

77.32259170380527

### Activity

In [96]:
#Viendo los valores que contiene Activity y sus cantidades
df['Activity'].value_counts()

Activity
Surfing                                                                                                                                                                                                                                                           1073
Swimming                                                                                                                                                                                                                                                           881
Fishing                                                                                                                                                                                                                                                            371
Spearfishing                                                                                                                                                                                                                                                       347
Wading                                                                                                                                                                                                                                                             163
Bathing                                                                                                                                                                                                                                                            141
Snorkeling                                                                                                                                                                                                                                                         122
Standing                                                                                                                                                                                                                                                           110
Diving                                                                                                                                                                                                                                                             106
Scuba diving                                                                                                                                                                                                                                                        69
Body boarding                                                                                                                                                                                                                                                       62
Body surfing                                                                                                                                                                                                                                                        47
Swimming                                                                                                                                                                                                                                                            41
Boogie boarding                                                                                                                                                                                                                                                     37
Kayaking                                                                                                                                                                                                                                                            36
Treading water                                                                                                                                                                                                                                                      31
Fell overboard                                                                                                                                                                                                                                                      29
Pearl diving                                                                                                                                                                                                                                                        28
Free diving                                                                                                                                                                                                                                                         28
Windsurfing                                                                                                                                                                                                                                                         20
Boogie Boarding                                                                                                                                                                                                                                                     18
Walking                                                                                                                                                                                                                                                             15
Floating                                                                                                                                                                                                                                                            15
Surf fishing                                                                                                                                                                                                                                                        12
Canoeing                                                                                                                                                                                                                                                            12
Surf-skiing                                                                                                                                                                                                                                                         12
Playing                                                                                                                                                                                                                                                             12
Paddle boarding                                                                                                                                                                                                                                                     11
Freediving                                                                                                                                                                                                                                                          11
Surf skiing                                                                                                                                                                                                                                                         11
Surf skiing                                                                                                                                                                                                                                                         11
Fishing                                                                                                                                                                                                                                                             11
Kayak Fishing                                                                                                                                                                                                                                                        9
Stand-Up Paddleboarding                                                                                                                                                                                                                                              9
Scuba Diving                                                                                                                                                                                                                                                         9
Fishing for sharks                                                                                                                                                                                                                                                   9
Diving for trochus                                                                                                                                                                                                                                                   8
Sitting on surfboard                                                                                                                                                                                                                                                 8
Fell into the water                                                                                                                                                                                                                                                  8
Kayak fishing                                                                                                                                                                                                                                                        7
Surfing (sitting on his board)                                                                                                                                                                                                                                       7
Free diving for abalone                                                                                                                                                                                                                                              7
Shark fishing                                                                                                                                                                                                                                                        7
Sponge diving                                                                                                                                                                                                                                                        7
Floating on his back                                                                                                                                                                                                                                                 6
Kite Surfing                                                                                                                                                                                                                                                         6
Kite surfing                                                                                                                                                                                                                                                         6
Sea disaster                                                                                                                                                                                                                                                         6
Body Boarding                                                                                                                                                                                                                                                        6
Skindiving                                                                                                                                                                                                                                                           6
Paddleskiing                                                                                                                                                                                                                                                         5
Freedom swimming                                                                                                                                                                                                                                                     5
Fishing on a boat                                                                                                                                                                                                                                                    5
Dangling feet in the water                                                                                                                                                                                                                                           5
Feeding sharks                                                                                                                                                                                                                                                       5
Diving for abalone                                                                                                                                                                                                                                                   5
Rowing                                                                                                                                                                                                                                                               5
Spearfishing on Scuba                                                                                                                                                                                                                                                5
Surfing                                                                                                                                                                                                                                                              5
Jumped into the water                                                                                                                                                                                                                                                4
Jumping                                                                                                                                                                                                                                                              4
Kayaking / Fishing                                                                                                                                                                                                                                                   4
Paddling on surfboard                                                                                                                                                                                                                                                4
Freedom Swimming                                                                                                                                                                                                                                                     4
Boat swamped                                                                                                                                                                                                                                                         4
Scuba diving (but on surface)                                                                                                                                                                                                                                        4
Body Surfing                                                                                                                                                                                                                                                         4
Sailing                                                                                                                                                                                                                                                              4
Hard hat diving                                                                                                                                                                                                                                                      4
Sitting on gunwale of boat                                                                                                                                                                                                                                           4
Scuba diving (submerged)                                                                                                                                                                                                                                             4
Diving for coins                                                                                                                                                                                                                                                     4
Lifesaving drill                                                                                                                                                                                                                                                     4
Body-boarding                                                                                                                                                                                                                                                        4
Wade Fishing                                                                                                                                                                                                                                                         4
Shipwreck                                                                                                                                                                                                                                                            4

In [97]:
#revisando cuantos nulos hay en columna Activity 
df['Activity'].isna().sum()

302

In [98]:
#Los pasamos a minusculas y quitamos espacios para ver si hay coincidencias entre los valores
df['Activity'] = df['Activity'].str.strip().str.lower()

In [99]:
#ver si tenia valores nulos escritos como print y pasarlos a valor np.nan
df[df['Activity'].astype(str).str.lower().isin(['nan', 'none', 'null', ''])]['Activity'].value_counts()

Activity
    1
Name: count, dtype: int64

In [100]:
#Lista de categorías frecuentes para poder agrupar valores
frequent_categories = [
    'surfing', 'swimming', 'fishing', 'spearfishing', 'wading', 'bathing',
    'diving', 'snorkeling', 'standing', 'scuba diving', 'body boarding',
    'boogie boarding', 'body surfing', 'kayaking', 'free diving', 'treading water',
    'fell overboard', 'pearl diving', 'surf skiing', 'windsurfing', 'floating',
    'walking', 'canoeing', 'kayak fishing', 'shark fishing', 'drifting', 'boating', 'sailing'
]

In [101]:
#funcion creada para que itere en la lista de frenquent_categories y si consigue alguna palabra que este en frequent_categories
#la almacene en la categoria correspondiente, sino que la incluya en un categoria llamada other
def map_activity(activity):
    if pd.isna(activity):
        return np.nan
    for category in frequent_categories:
        if category in activity.lower():
            return category
    return 'other'

In [102]:
#aplicamos la funcion map_activy en nuestra columna y vemos el filtrado 
df['Activity'] = df['Activity'].apply(map_activity)

# Ver resultados
print(df['Activity'].value_counts(dropna=False))

Activity
surfing            1235
swimming           1107
fishing            1024
other               717
diving              475
NaN                 302
wading              178
bathing             167
standing            139
snorkeling          130
body boarding        69
boogie boarding      55
fell overboard       51
floating             46
kayaking             40
treading water       36
surf skiing          22
walking              20
canoeing             12
sailing               9
Name: count, dtype: int64

### Columna "Country"

In [103]:
#Observacion de valor unicos
df['Country'].unique()

array(['Australia', 'US Virgin Islands', 'New Caledonia', 'USA',
       'French Polynesia', 'Samoa', 'Columbia', 'Costa Rica', 'Bahamas',
       'Puerto Rico', 'Spain', 'Canary Islands', 'South Africa',
       'Vanuatu', 'Jamaica', 'Israel', 'Mexico', 'Maldives',
       'Philippines', 'Turks and Caicos', 'Mozambique', 'Egypt',
       'Thailand', 'New Zealand', 'Hawaii', 'Honduras', 'Indonesia',
       'Morocco', 'Belize', 'Maldive Islands', 'Tobago', 'AUSTRALIA',
       'INDIA', 'TRINIDAD', 'BAHAMAS', 'SOUTH AFRICA', 'MEXICO',
       'NEW ZEALAND', 'EGYPT', 'BELIZE', 'Coral Sea', 'SPAIN', 'PORTUGAL',
       'SAMOA', 'COLOMBIA', 'ECUADOR', 'FRENCH POLYNESIA',
       'NEW CALEDONIA', 'TURKS and CaICOS', 'CUBA', 'BRAZIL', 'FIJI',
       'MeXICO', 'ENGLAND', 'JAPAN', 'INDONESIA', 'JAMAICA', 'MALDIVES',
       'THAILAND', 'COLUMBIA', 'British Overseas Territory', 'CANADA',
       'JORDAN', 'ST KITTS / NEVIS', 'ST MARTIN', 'SEYCHELLES',
       'PAPUA NEW GUINEA', 'ISRAEL', 'REUNION ISLAND', 'CHINA', 'IRELAND',
       'ITALY', 'COSTA RICA', 'MALAYSIA', nan, 'MAURITIUS',
       'SOLOMON ISLANDS', 'ST HELENA, British overseas territory',
       'REUNION', 'UNITED KINGDOM', 'UNITED ARAB EMIRATES', 'PHILIPPINES',
       'Fiji', 'DOMINICAN REPUBLIC', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO',
       'ST. MARTIN', 'FRANCE', 'TRINIDAD & TOBAGO', 'KIRIBATI',
       'DIEGO GARCIA', 'TAIWAN', 'PALESTINIAN TERRITORIES', 'GUAM',
       'NIGERIA', 'TONGA', 'SCOTLAND', 'CHILE', 'KENYA', 'RUSSIA',
       'TURKS & CAICOS', 'AZORES', 'SOUTH KOREA', 'MALTA', 'VIETNAM',
       'MADAGASCAR', 'UNITED ARAB EMIRATES (UAE)', 'PANAMA', 'SOMALIA',
       'CROATIA', 'NORWAY', 'Sierra Leone', 'ATLANTIC OCEAN',
       'ST. MAARTIN', 'GRAND CAYMAN', 'VANUATU', 'MEXICO ', 'VENEZUELA',
       ' TONGA', 'URUGUAY', 'MICRONESIA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'SENEGAL', 'EGYPT / ISRAEL',
       'NORTHERN ARABIAN SEA', 'HONG KONG', 'EL SALVADOR',
       'CARIBBEAN SEA', 'ANGOLA', 'IRAN', 'TUNISIA', 'NAMIBIA', 'GREECE',
       'NORTH ATLANTIC OCEAN', 'SOUTH CHINA SEA', 'BERMUDA', 'PALAU',
       'WESTERN SAMOA', 'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA',
       'SRI LANKA', 'IRAQ', 'TURKEY', 'SINGAPORE', 'NEW BRITAIN', 'SUDAN',
       'JOHNSTON ISLAND', 'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'MONTENEGRO', 'YEMEN', 'THE BALKANS',
       'SUDAN?', 'ARGENTINA', 'MARTINIQUE', 'NETHERLANDS ANTILLES',
       'LIBERIA', 'SAUDI ARABIA', 'NORTHERN MARIANA ISLANDS',
       'IRAN / IRAQ', 'SIERRA LEONE', ' PHILIPPINES', 'CENTRAL PACIFIC',
       'INDIAN OCEAN', 'SOLOMON ISLANDS / VANUATU',
       'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'MID-PACIFC OCEAN',
       'CURACAO', 'ICELAND', 'CAPE VERDE', 'HONDURAS', 'NICARAGUA',
       'MONACO', 'GUYANA', 'BARBADOS', 'HAITI', 'SAN DOMINGO', 'KUWAIT',
       'LIBYA', 'YEMEN ', 'FALKLAND ISLANDS', 'CRETE', 'CYPRUS', 'EGYPT ',
       'WEST INDIES', 'BURMA', 'LEBANON', 'BRITISH NEW GUINEA', 'CEYLON',
       'OCEAN', 'GEORGIA', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'JAVA', 'MEDITERRANEAN SEA', 'Between PORTUGAL & INDIA'],
      dtype=object)

In [104]:
#unificando para que todo sea mayuscula y quitando espacio en blanco 
df['Country'] = df['Country'].str.upper().str.strip()

In [105]:
#Observamos que se unifican algunos valores 
df['Country'].value_counts()

Country
USA                                      2267
AUSTRALIA                                1238
SOUTH AFRICA                              468
BAHAMAS                                   127
NEW ZEALAND                               120
PAPUA NEW GUINEA                          112
BRAZIL                                     98
MEXICO                                     89
FIJI                                       60
REUNION                                    52
NEW CALEDONIA                              50
ITALY                                      47
PHILIPPINES                                46
EGYPT                                      45
CUBA                                       41
MOZAMBIQUE                                 38
SPAIN                                      33
FRENCH POLYNESIA                           33
PANAMA                                     29
INDIA                                      28
JAMAICA                                    28
SOLOMON ISLANDS                            26
JAPAN                                      25
IRAN                                       25
HONG KONG                                  23
CROATIA                                    22
ENGLAND                                    22
INDONESIA                                  20
TONGA                                      16
COSTA RICA                                 16
PACIFIC OCEAN                              14
VIETNAM                                    13
THAILAND                                   12
VANUATU                                    12
GREECE                                     11
SRI LANKA                                  11
ECUADOR                                    11
ATLANTIC OCEAN                             11
CANADA                                     10
MAURITIUS                                  10
VENEZUELA                                  10
SOUTH ATLANTIC OCEAN                       10
COLUMBIA                                    9
MARSHALL ISLANDS                            9
TURKEY                                      9
UNITED KINGDOM                              9
TAIWAN                                      9
SAMOA                                       9
KENYA                                       8
CHILE                                       8
SENEGAL                                     8
SIERRA LEONE                                8
IRAQ                                        8
SOUTH KOREA                                 8
NEW GUINEA                                  8
CHINA                                       8
BERMUDA                                     7
ISRAEL                                      7
FRANCE                                      7
SEYCHELLES                                  7
NEW BRITAIN                                 6
MADAGASCAR                                  6
MALDIVES                                    6
OKINAWA                                     6
YEMEN                                       6
SINGAPORE                                   5
BARBADOS                                    5
NORTH PACIFIC OCEAN                         5
PALAU                                       5
BELIZE                                      5
HONDURAS                                    5
SCOTLAND                                    5
SOMALIA                                     4
MID ATLANTIC OCEAN                          4
INDIAN OCEAN                                4
NICARAGUA                                   4
CARIBBEAN SEA                               4
GRENADA                                     4
LIBYA                                       4
TANZANIA                                    4
MALTA                                       4
DOMINICAN REPUBLIC                          4
TURKS & CAICOS                              4
RUSSIA                                      4
REUNION ISLAND                              4
TURKS AND CAICOS                            3
MARTINIQUE                                  3
AMERICAN SAMOA                              3
PERSIAN GULF                                3
MALDIVE ISLANDS                             3
TOBAGO                                      3
PORTUGAL                                    3
MALAYSIA                                    3
NORTH ATLANTIC OCEAN                        3
CEYLON                                      3
NIGERIA                                     3
KIRIBATI                                    3
MICRONESIA                                  3
GUAM                                        3
CENTRAL PACIFIC                             2
IRELAND                                     2
GUYANA                                      2
AZORES                                      2
PUERTO RICO                                 2
SOUTH PACIFIC OCEAN                         2
TRINIDAD & TOBAGO                           2
SUDAN                                       2
WEST INDIES                                 2
BURMA                                       2
LEBANON                                     2
MONTENEGRO                                  2
HAITI                                       2
UNITED ARAB EMIRATES                        2
SOUTHWEST PACIFIC OCEAN                     2
ST HELENA, BRITISH OVERSEAS TERRITORY       2
NAMIBIA                                     2
TUNISIA                                     2
LIBERIA                                     2
URUGUAY                                     2
GUINEA                                      2
EL SALVADOR                                 2
JAVA                                        1
CANARY ISLANDS                              1
MEDITERRANEAN SEA                           1
SOLOMON ISLANDS / VANUATU                   1
BAY OF BENGAL                               1
MONACO                                      1
CAPE VERDE                                  1
ICELAND                                     1
CURACAO                                     1
MID-PACIFC OCEAN                            1
AFRICA                                      1
GHANA                                       1
SAN DOMINGO                                 1
PERU                                        1
COOK ISLANDS                                1
EQUATORIAL GUINEA / CAMEROON                1
ANDAMAN ISLANDS                             1
INDIAN OCEAN?                               1
GEORGIA                                     1
ALGERIA                                     1
OCEAN                                       1
IRAN / IRAQ                                 1
BRITISH NEW GUINEA                          1
COAST OF AFRICA                             1
CRETE                                       1
FALKLAND ISLANDS                            1
KUWAIT                                      1
TASMAN SEA                                  1
CYPRUS                                      1
MOROCCO                                     1
NORTHERN MARIANA ISLANDS                    1
SAUDI ARABIA                                1
ST KITTS / NEVIS                            1
ST MARTIN                                   1
BRITISH ISLES                               1
WESTERN SAMOA                               1
SOUTH CHINA SEA                             1
ANGOLA                                      1
ARUBA                                       1
NORTHERN ARABIAN SEA                        1
EGYPT / ISRAEL                              1
ST. MARTIN                                  1
US VIRGIN ISLANDS                           1
DIEGO GARCIA                                1
GRAND CAYMAN                                1
ST. MAARTIN                                 1
PALESTINIAN TERRITORIES                     1
NORWAY                                      1
UNITED ARAB EMIRATES (UAE)                  1
JORDAN                                      1
BRITISH OVERSEAS TERRITORY                  1
COLOMBIA                                    1
ANDAMAN / NICOBAR ISLANDAS                  1
NETHERLANDS ANTILLES                        1
ARGENTINA                                   1
SUDAN?                                      1
THE BALKANS                                 1
HAWAII                                      1
MAYOTTE                                     1
GABON                                       1
NORTH SEA                                   1
JOHNSTON ISLAND                             1
RED SEA / INDIAN OCEAN                      1
BRITISH WEST INDIES                         1
ADMIRALTY ISLANDS                           1
FEDERATED STATES OF MICRONESIA              1
TRINIDAD                                    1
RED SEA                                     1
CORAL SEA                                   1
BETWEEN PORTUGAL & INDIA                    1
Name: count, dtype: int64

In [106]:
#Aqui toma el primer valor al separa valor/valor
df['Country'] = df['Country'].str.split('/').str[0].str.strip()

In [107]:
#lo pasamos a series para observar con cuantos valores unicos estamos tratando 
pd.Series(df['Country'].unique())

0                                  AUSTRALIA
1                          US VIRGIN ISLANDS
2                              NEW CALEDONIA
3                                        USA
4                           FRENCH POLYNESIA
5                                      SAMOA
6                                   COLUMBIA
7                                 COSTA RICA
8                                    BAHAMAS
9                                PUERTO RICO
10                                     SPAIN
11                            CANARY ISLANDS
12                              SOUTH AFRICA
13                                   VANUATU
14                                   JAMAICA
15                                    ISRAEL
16                                    MEXICO
17                                  MALDIVES
18                               PHILIPPINES
19                          TURKS AND CAICOS
20                                MOZAMBIQUE
21                                     EGYPT
22                                  THAILAND
23                               NEW ZEALAND
24                                    HAWAII
25                                  HONDURAS
26                                 INDONESIA
27                                   MOROCCO
28                                    BELIZE
29                           MALDIVE ISLANDS
30                                    TOBAGO
31                                     INDIA
32                                  TRINIDAD
33                                 CORAL SEA
34                                  PORTUGAL
35                                  COLOMBIA
36                                   ECUADOR
37                                      CUBA
38                                    BRAZIL
39                                      FIJI
40                                   ENGLAND
41                                     JAPAN
42                BRITISH OVERSEAS TERRITORY
43                                    CANADA
44                                    JORDAN
45                                  ST KITTS
46                                 ST MARTIN
47                                SEYCHELLES
48                          PAPUA NEW GUINEA
49                            REUNION ISLAND
50                                     CHINA
51                                   IRELAND
52                                     ITALY
53                                  MALAYSIA
54                                       NaN
55                                 MAURITIUS
56                           SOLOMON ISLANDS
57     ST HELENA, BRITISH OVERSEAS TERRITORY
58                                   REUNION
59                            UNITED KINGDOM
60                      UNITED ARAB EMIRATES
61                        DOMINICAN REPUBLIC
62                                     ARUBA
63                                ST. MARTIN
64                                    FRANCE
65                         TRINIDAD & TOBAGO
66                                  KIRIBATI
67                              DIEGO GARCIA
68                                    TAIWAN
69                   PALESTINIAN TERRITORIES
70                                      GUAM
71                                   NIGERIA
72                                     TONGA
73                                  SCOTLAND
74                                     CHILE
75                                     KENYA
76                                    RUSSIA
77                            TURKS & CAICOS
78                                    AZORES
79                               SOUTH KOREA
80                                     MALTA
81                                   VIETNAM
82                                MADAGASCAR
83                UNITED ARAB EMIRATES (UAE)
84                                    PANAMA
85                                   SOMALIA
86                                   CROATIA
87                                    NORWAY
88                              SIERRA LEONE
89                            ATLANTIC OCEAN
90                               ST. MAARTIN
91                              GRAND CAYMAN
92                                 VENEZUELA
93                                   URUGUAY
94                                MICRONESIA
95                                   OKINAWA
96                                  TANZANIA
97                          MARSHALL ISLANDS
98                                   SENEGAL
99                      NORTHERN ARABIAN SEA
100                                HONG KONG
101                              EL SALVADOR
102                            CARIBBEAN SEA
103                                   ANGOLA
104                                     IRAN
105                                  TUNISIA
106                                  NAMIBIA
107                                   GREECE
108                     NORTH ATLANTIC OCEAN
109                          SOUTH CHINA SEA
110                                  BERMUDA
111                                    PALAU
112                            WESTERN SAMOA
113                            PACIFIC OCEAN
114                            BRITISH ISLES
115                                  GRENADA
116                                SRI LANKA
117                                     IRAQ
118                                   TURKEY
119                                SINGAPORE
120                              NEW BRITAIN
121                                    SUDAN
122                          JOHNSTON ISLAND
123                      SOUTH PACIFIC OCEAN
124                               NEW GUINEA
125                                  RED SEA
126                      NORTH PACIFIC OCEAN
127           FEDERATED STATES OF MICRONESIA
128                       MID ATLANTIC OCEAN
129                        ADMIRALTY ISLANDS
130                      BRITISH WEST INDIES
131                     SOUTH ATLANTIC OCEAN
132                             PERSIAN GULF
133                                NORTH SEA
134                                NICARAGUA
135                           AMERICAN SAMOA
136                                  ANDAMAN
137                                    GABON
138                                  MAYOTTE
139                               MONTENEGRO
140                                    YEMEN
141                              THE BALKANS
142                                   SUDAN?
143                                ARGENTINA
144                               MARTINIQUE
145                     NETHERLANDS ANTILLES
146                                  LIBERIA
147                             SAUDI ARABIA
148                 NORTHERN MARIANA ISLANDS
149                          CENTRAL PACIFIC
150                             INDIAN OCEAN
151                  SOUTHWEST PACIFIC OCEAN
152                            BAY OF BENGAL
153                         MID-PACIFC OCEAN
154                                  CURACAO
155                                  ICELAND
156                               CAPE VERDE
157                                   MONACO
158                                   GUYANA
159                                 BARBADOS
160                                    HAITI
161                              SAN DOMINGO
162                                   KUWAIT
163                                    LIBYA
164                         FALKLAND ISLANDS
165                                    CRETE
166                                   CYPRUS
167                              WEST INDIES
168                                    BURMA
169                                  LEBANON
170                       BRITISH NEW GUINEA
171                                   CEYLON
172                                    OCEAN
173                                  GEORGIA
174                            INDIAN OCEAN?
175                                   GUINEA
176                          ANDAMAN ISLANDS
177                        EQUATORIAL GUINEA
178                             COOK ISLANDS
179                                     PERU
180                                   AFRICA
181                                  ALGERIA
182                          COAST OF AFRICA
183                               TASMAN SEA
184                                    GHANA
185                                     JAVA
186                        MEDITERRANEAN SEA
187                 BETWEEN PORTUGAL & INDIA
dtype: object

In [ ]:
# Países con múltiples nombres o abreviaciones
country_mapping = {    
    'ST KITTS / NEVIS': 'SAINT KITTS AND NEVIS',
    'ST KITTS': 'SAINT KITTS AND NEVIS',
    'NEVIS': 'SAINT KITTS AND NEVIS',
    'TRINIDAD & TOBAGO': 'TRINIDAD AND TOBAGO',
    'TRINIDAD': 'TRINIDAD AND TOBAGO',
    'TOBAGO': 'TRINIDAD AND TOBAGO',
    'TURKS & CAICOS': 'TURKS AND CAICOS',
    'TURKS': 'TURKS AND CAICOS',
    'ST. MARTIN': 'SAINT MARTIN',
    'ST. MAARTIN': 'SAINT MARTIN',
    'MALDIVE ISLANDS': 'MALDIVES',
    'CEYLON': 'SRI LANKA',
    'CEYLON (SRI LANKA)': 'SRI LANKA',
    'COLUMBIA': 'COLOMBIA',
    'OKINAWA': 'JAPAN',
    'WESTERN SAMOA': 'SAMOA',
    'BRITISH NEW GUINEA': 'PAPUA NEW GUINEA',
    'NEW BRITAIN': 'PAPUA NEW GUINEA',
    
    # Territorios y países especiales
    'BRITISH VIRGIN ISLANDS': 'UNITED KINGDOM',
    'ST HELENA, BRITISH OVERSEAS TERRITORY': 'UNITED KINGDOM',
    'UNITED ARAB EMIRATES (UAE)': 'UNITED ARAB EMIRATES',
    'HAWAII': 'USA',
    'CANARY ISLANDS': 'SPAIN',
    'ANDAMAN ISLANDS': 'INDIA',
    'GUAM (US TERRITORY)': 'USA',
    
    # Zonas geográficas no país → OTHER
    'CORAL SEA': 'OTHER',
    'ATLANTIC OCEAN': 'OTHER',
    'CARIBBEAN SEA': 'OTHER',
    'COAST OF AFRICA': 'OTHER',
    'RED SEA?': 'OTHER',
    'ASIA?': 'OTHER',
    'DIEGO GARCIA': 'OTHER',
    'REUNION ISLAND': 'OTHER',
    'GULF OF ADEN': 'OTHER',
    'TASMAN SEA': 'OTHER',
    'NORTH ATLANTIC OCEAN': 'OTHER',
    'SOUTH CHINA SEA': 'OTHER',
    'PACIFIC OCEAN': 'OTHER',
    'JOHNSTON ISLAND': 'OTHER',
    'SOUTH PACIFIC OCEAN': 'OTHER',
    'WEST INDIES': 'OTHER',
    'OCEAN': 'OTHER',
    'MEDITERRANEAN SEA': 'OTHER',
    'ROATAN': 'OTHER',
    'NORTHERN ARABIAN SEA': 'OTHER',
    'INDEPENDENT STATES': 'OTHER',
    'KOREA': 'OTHER'
}

In [109]:
df['Country'] = df['Country'].replace(country_mapping)

In [110]:
df['Country'].unique()

array(['AUSTRALIA', 'US VIRGIN ISLANDS', 'NEW CALEDONIA', 'USA',
       'FRENCH POLYNESIA', 'SAMOA', 'COLOMBIA', 'COSTA RICA', 'BAHAMAS',
       'PUERTO RICO', 'SPAIN', 'SOUTH AFRICA', 'VANUATU', 'JAMAICA',
       'ISRAEL', 'MEXICO', 'MALDIVES', 'PHILIPPINES', 'TURKS AND CAICOS',
       'MOZAMBIQUE', 'EGYPT', 'THAILAND', 'NEW ZEALAND', 'HONDURAS',
       'INDONESIA', 'MOROCCO', 'BELIZE', 'TRINIDAD AND TOBAGO', 'INDIA',
       'OTHER', 'PORTUGAL', 'ECUADOR', 'CUBA', 'BRAZIL', 'FIJI',
       'ENGLAND', 'JAPAN', 'BRITISH OVERSEAS TERRITORY', 'CANADA',
       'JORDAN', 'SAINT KITTS AND NEVIS', 'ST MARTIN', 'SEYCHELLES',
       'PAPUA NEW GUINEA', 'CHINA', 'IRELAND', 'ITALY', 'MALAYSIA', nan,
       'MAURITIUS', 'SOLOMON ISLANDS', 'UNITED KINGDOM', 'REUNION',
       'UNITED ARAB EMIRATES', 'DOMINICAN REPUBLIC', 'ARUBA',
       'SAINT MARTIN', 'FRANCE', 'KIRIBATI', 'TAIWAN',
       'PALESTINIAN TERRITORIES', 'GUAM', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CHILE', 'KENYA', 'RUSSIA', 'AZORES', 'SOUTH KOREA', 'MALTA',
       'VIETNAM', 'MADAGASCAR', 'PANAMA', 'SOMALIA', 'CROATIA', 'NORWAY',
       'SIERRA LEONE', 'GRAND CAYMAN', 'VENEZUELA', 'URUGUAY',
       'MICRONESIA', 'TANZANIA', 'MARSHALL ISLANDS', 'SENEGAL',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'IRAN', 'TUNISIA', 'NAMIBIA',
       'GREECE', 'BERMUDA', 'PALAU', 'BRITISH ISLES', 'GRENADA',
       'SRI LANKA', 'IRAQ', 'TURKEY', 'SINGAPORE', 'SUDAN', 'NEW GUINEA',
       'RED SEA', 'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'NORTH SEA', 'NICARAGUA',
       'AMERICAN SAMOA', 'ANDAMAN', 'GABON', 'MAYOTTE', 'MONTENEGRO',
       'YEMEN', 'THE BALKANS', 'SUDAN?', 'ARGENTINA', 'MARTINIQUE',
       'NETHERLANDS ANTILLES', 'LIBERIA', 'SAUDI ARABIA',
       'NORTHERN MARIANA ISLANDS', 'CENTRAL PACIFIC', 'INDIAN OCEAN',
       'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'MID-PACIFC OCEAN',
       'CURACAO', 'ICELAND', 'CAPE VERDE', 'MONACO', 'GUYANA', 'BARBADOS',
       'HAITI', 'SAN DOMINGO', 'KUWAIT', 'LIBYA', 'FALKLAND ISLANDS',
       'CRETE', 'CYPRUS', 'BURMA', 'LEBANON', 'GEORGIA', 'INDIAN OCEAN?',
       'GUINEA', 'EQUATORIAL GUINEA', 'COOK ISLANDS', 'PERU', 'AFRICA',
       'ALGERIA', 'GHANA', 'JAVA', 'BETWEEN PORTUGAL & INDIA'],
      dtype=object)

In [111]:
pd.Series(df['Country'].unique())

0                           AUSTRALIA
1                   US VIRGIN ISLANDS
2                       NEW CALEDONIA
3                                 USA
4                    FRENCH POLYNESIA
5                               SAMOA
6                            COLOMBIA
7                          COSTA RICA
8                             BAHAMAS
9                         PUERTO RICO
10                              SPAIN
11                       SOUTH AFRICA
12                            VANUATU
13                            JAMAICA
14                             ISRAEL
15                             MEXICO
16                           MALDIVES
17                        PHILIPPINES
18                   TURKS AND CAICOS
19                         MOZAMBIQUE
20                              EGYPT
21                           THAILAND
22                        NEW ZEALAND
23                           HONDURAS
24                          INDONESIA
25                            MOROCCO
26                             BELIZE
27                TRINIDAD AND TOBAGO
28                              INDIA
29                              OTHER
30                           PORTUGAL
31                            ECUADOR
32                               CUBA
33                             BRAZIL
34                               FIJI
35                            ENGLAND
36                              JAPAN
37         BRITISH OVERSEAS TERRITORY
38                             CANADA
39                             JORDAN
40              SAINT KITTS AND NEVIS
41                          ST MARTIN
42                         SEYCHELLES
43                   PAPUA NEW GUINEA
44                              CHINA
45                            IRELAND
46                              ITALY
47                           MALAYSIA
48                                NaN
49                          MAURITIUS
50                    SOLOMON ISLANDS
51                     UNITED KINGDOM
52                            REUNION
53               UNITED ARAB EMIRATES
54                 DOMINICAN REPUBLIC
55                              ARUBA
56                       SAINT MARTIN
57                             FRANCE
58                           KIRIBATI
59                             TAIWAN
60            PALESTINIAN TERRITORIES
61                               GUAM
62                            NIGERIA
63                              TONGA
64                           SCOTLAND
65                              CHILE
66                              KENYA
67                             RUSSIA
68                             AZORES
69                        SOUTH KOREA
70                              MALTA
71                            VIETNAM
72                         MADAGASCAR
73                             PANAMA
74                            SOMALIA
75                            CROATIA
76                             NORWAY
77                       SIERRA LEONE
78                       GRAND CAYMAN
79                          VENEZUELA
80                            URUGUAY
81                         MICRONESIA
82                           TANZANIA
83                   MARSHALL ISLANDS
84                            SENEGAL
85                          HONG KONG
86                        EL SALVADOR
87                             ANGOLA
88                               IRAN
89                            TUNISIA
90                            NAMIBIA
91                             GREECE
92                            BERMUDA
93                              PALAU
94                      BRITISH ISLES
95                            GRENADA
96                          SRI LANKA
97                               IRAQ
98                             TURKEY
99                          SINGAPORE
100                             SUDAN
101                        NEW GUINEA
102                           RED SEA
103               NORTH PACIFIC OCEAN
104    FEDERATED STATES OF MICRONESIA
105                MID ATLANTIC OCEAN
106                 ADMIRALTY ISLANDS
107               BRITISH WEST INDIES
108              SOUTH ATLANTIC OCEAN
109                      PERSIAN GULF
110                         NORTH SEA
111                         NICARAGUA
112                    AMERICAN SAMOA
113                           ANDAMAN
114                             GABON
115                           MAYOTTE
116                        MONTENEGRO
117                             YEMEN
118                       THE BALKANS
119                            SUDAN?
120                         ARGENTINA
121                        MARTINIQUE
122              NETHERLANDS ANTILLES
123                           LIBERIA
124                      SAUDI ARABIA
125          NORTHERN MARIANA ISLANDS
126                   CENTRAL PACIFIC
127                      INDIAN OCEAN
128           SOUTHWEST PACIFIC OCEAN
129                     BAY OF BENGAL
130                  MID-PACIFC OCEAN
131                           CURACAO
132                           ICELAND
133                        CAPE VERDE
134                            MONACO
135                            GUYANA
136                          BARBADOS
137                             HAITI
138                       SAN DOMINGO
139                            KUWAIT
140                             LIBYA
141                  FALKLAND ISLANDS
142                             CRETE
143                            CYPRUS
144                             BURMA
145                           LEBANON
146                           GEORGIA
147                     INDIAN OCEAN?
148                            GUINEA
149                 EQUATORIAL GUINEA
150                      COOK ISLANDS
151                              PERU
152                            AFRICA
153                           ALGERIA
154                             GHANA
155                              JAVA
156          BETWEEN PORTUGAL & INDIA
dtype: object

In [112]:
df['Country'].value_counts()

Country
USA                               2268
AUSTRALIA                         1238
SOUTH AFRICA                       468
BAHAMAS                            127
NEW ZEALAND                        120
PAPUA NEW GUINEA                   119
BRAZIL                              98
MEXICO                              89
FIJI                                60
REUNION                             52
NEW CALEDONIA                       50
OTHER                               49
ITALY                               47
EGYPT                               46
PHILIPPINES                         46
CUBA                                41
MOZAMBIQUE                          38
SPAIN                               34
FRENCH POLYNESIA                    33
JAPAN                               31
PANAMA                              29
INDIA                               29
JAMAICA                             28
SOLOMON ISLANDS                     27
IRAN                                26
HONG KONG                           23
ENGLAND                             22
CROATIA                             22
INDONESIA                           20
TONGA                               16
COSTA RICA                          16
SRI LANKA                           14
VIETNAM                             13
THAILAND                            12
VANUATU                             12
GREECE                              11
UNITED KINGDOM                      11
ECUADOR                             11
SOUTH ATLANTIC OCEAN                10
MAURITIUS                           10
VENEZUELA                           10
COLOMBIA                            10
CANADA                              10
SAMOA                               10
MALDIVES                             9
TURKEY                               9
TAIWAN                               9
MARSHALL ISLANDS                     9
SENEGAL                              8
SOUTH KOREA                          8
NEW GUINEA                           8
SIERRA LEONE                         8
KENYA                                8
CHILE                                8
IRAQ                                 8
CHINA                                8
ISRAEL                               7
TURKS AND CAICOS                     7
FRANCE                               7
BERMUDA                              7
SEYCHELLES                           7
MADAGASCAR                           6
YEMEN                                6
TRINIDAD AND TOBAGO                  6
SCOTLAND                             5
BARBADOS                             5
PALAU                                5
NORTH PACIFIC OCEAN                  5
BELIZE                               5
HONDURAS                             5
SINGAPORE                            5
TANZANIA                             4
MALTA                                4
SOMALIA                              4
INDIAN OCEAN                         4
GRENADA                              4
LIBYA                                4
NICARAGUA                            4
RUSSIA                               4
MID ATLANTIC OCEAN                   4
DOMINICAN REPUBLIC                   4
NIGERIA                              3
MALAYSIA                             3
PORTUGAL                             3
KIRIBATI                             3
UNITED ARAB EMIRATES                 3
GUAM                                 3
MICRONESIA                           3
AMERICAN SAMOA                       3
MARTINIQUE                           3
PERSIAN GULF                         3
HAITI                                2
LIBERIA                              2
BURMA                                2
RED SEA                              2
MONTENEGRO                           2
CENTRAL PACIFIC                      2
GUYANA                               2
SOUTHWEST PACIFIC OCEAN              2
EL SALVADOR                          2
SUDAN                                2
IRELAND                              2
SAINT MARTIN                         2
LEBANON                              2
GUINEA                               2
URUGUAY                              2
AZORES                               2
TUNISIA                              2
NAMIBIA                              2
PUERTO RICO                          2
GHANA                                1
ICELAND                              1
PERU                                 1
JAVA                                 1
ALGERIA                              1
MONACO                               1
AFRICA                               1
CAPE VERDE                           1
SAN DOMINGO                          1
COOK ISLANDS                         1
EQUATORIAL GUINEA                    1
KUWAIT                               1
INDIAN OCEAN?                        1
FALKLAND ISLANDS                     1
MID-PACIFC OCEAN                     1
GEORGIA                              1
CRETE                                1
CYPRUS                               1
CURACAO                              1
ST MARTIN                            1
BAY OF BENGAL                        1
NORTHERN MARIANA ISLANDS             1
SAINT KITTS AND NEVIS                1
JORDAN                               1
BRITISH OVERSEAS TERRITORY           1
ARUBA                                1
PALESTINIAN TERRITORIES              1
MOROCCO                              1
NORWAY                               1
GRAND CAYMAN                         1
US VIRGIN ISLANDS                    1
ANGOLA                               1
BRITISH ISLES                        1
FEDERATED STATES OF MICRONESIA       1
ADMIRALTY ISLANDS                    1
BRITISH WEST INDIES                  1
NORTH SEA                            1
ANDAMAN                              1
GABON                                1
MAYOTTE                              1
THE BALKANS                          1
SUDAN?                               1
ARGENTINA                            1
NETHERLANDS ANTILLES                 1
SAUDI ARABIA                         1
BETWEEN PORTUGAL & INDIA             1
Name: count, dtype: int64

### Columna Date

In [364]:
df['Date'].unique()

array(['10th January', '8th January', '3rd January ', ..., '1900-1905',
       '1883-1889', '1845-1853'], dtype=object)

In [365]:
def false_words(s):
    eliminate_words = [
        'Before', 'After', 'No date', 'Late',
        'Circa', 'Ca.', 'Letter dated'
    ]
    
    s = str(s).lower()
    #Recorre la lista eliminate_words comprueba si alguna de esas palabras esta dentro del texto 
    #devuelve True si al menos encuenta una 
    for word in eliminate_words:
        if word.lower() in s:
            return True
    
    return False

In [366]:
def extract_full_month(s):
    #lista de los meses
    months_full = [
        'January', 'February', 'March', 'April', 'May', 'June',
        'July', 'August', 'September', 'October', 'November', 'December'
    ]
    
    #
    months_abbreviate = []
    for m in months_full:
        months_abbreviate.append(m[:3])
    #flags=re.I -> hace la bisque a mayuscula y minusculas
    #crea pares con sus el nombre completo del mes y su abreviatura ('January', 'Jan')
    for m_full, m_abbr in zip(months_full, months_abbreviate):
        #primera condicion busca el nombre completo del mes y la segunda la abreviatura
        if re.search(rf'\b{m_full}\b', s, flags=re.I) or \
           re.search(rf'\b{m_abbr}\b', s, flags=re.I):
            return m_full
    
    return None

In [367]:
#esta funcion trabaja con un solo valor
#su trabajo es limpiar, validar y extraer el mes 
def parse_month(x):
    if pd.isna(x):
        return None
        
    s = str(x).strip()
        
    #Descartar fechas inciertas
    if false_words(s):
        return None
        
    #Extraer mes
    return extract_full_month(s)

In [368]:
def extract_full_month_strict(date_series):
    return date_series.apply(parse_month)

In [369]:
df['Month_full_strict'] = extract_full_month_strict(df['Date'])

In [370]:
print(df[['Date', 'Month_full_strict']])

                                                   Date Month_full_strict
0                                          10th January           January
1                                           8th January           January
2                                          3rd January            January
3                                         21st December          December
4                                         12th December          December
5                                          9th December          December
6                                        27th November           November
7                                        27th November           November
8                                         10th November          November
9                                          9th November          November
10                                         5th November          November
11                                         5th November          November
12                                         4th November          November
13                                         14th October           October
14                                         11th October           October
15                                          7th October           October
16                                       29th September         September
17                                       27th September         September
18                                        6th September         September
19                                        1st September         September
20                                          30th August            August
21                                          18th August            August
22                                          17th August            August
23                                          16th August            August
24                                           7th August            August
25                                           1st August            August
26                                            28th July              July
27                                            25th July              July
28                                            22nd July              July
29                                            20th July              July
30                                            19th July              July
31                                            18th July              July
32                                            15th July              July
33                                            6th July               July
34                                             6th July              July
35                                             4th July              July
36                                            29th June              June
37                                            25th June              June
38                                            22nd June              June
39                                            17th June              June
40                                  2025-06-11 00:00:00              None
41                                             31st May               May
42                                  2025-05-29 00:00:00              None
43                                  2025-05-26 00:00:00              None
44                                  2025-05-15 00:00:00              None
45                                  2025-05-08 00:00:00              None
46                                  2025-04-21 00:00:00              None
47                                  2025-04-20 00:00:00              None
48                                  2025-04-19 00:00:00              None
49                                  2025-04-12 00:00:00              None
50                                  2025-03-26 00:00:00              None
51                                  2025-03-10 00:00:00              None
52                                  2025-03-07 00:00:00              None
53                                  2025-02-27 00:00:00              None
54                                            27-Feb-25          February
55                                  2025-02-22 00:00:00              None
56                                  2025-02-22 00:00:00              None
57                                  2025-02-22 00:00:00              None
58                                  2025-02-10 00:00:00              None
59                                  2025-02-10 00:00:00              None
60                                  2025-02-07 00:00:00              None
61                                  2025-02-03 00:00:00              None
62                                  2025-01-23 00:00:00              None
63                                  2025-01-22 00:00:00              None
64                                  2025-01-03 00:00:00              None
65                                  2025-01-11 00:00:00              None
66                                  2025-01-02 00:00:00              None
67                                  2025-01-02 00:00:00              None
68                                  2024-12-30 00:00:00              None
69                                  2024-12-29 00:00:00              None
70                                  2024-12-29 00:00:00              None
71                                  2024-12-28 00:00:00              None
72                                  2024-12-02 00:00:00              None
73                                  2024-12-01 00:00:00              None
74                                  2024-11-30 00:00:00              None
75                                  2024-11-19 00:00:00              None
76                                  2024-11-15 00:00:00              None
77                                  2024-11-01 00:00:00              None
78                                  2024-10-31 00:00:00              None
79                                  2024-10-25 00:00:00              None
80                                  2024-10-14 00:00:00              None
81                                  2024-10-11 00:00:00              None
82                                  2024-09-26 00:00:00              None
83                                  2024-09-17 00:00:00              None
84                                  2024-09-16 00:00:00              None
85                                  2024-08-26 00:00:00              None
86                                  2024-08-06 00:00:00              None
87                                  2024-07-23 00:00:00              None
88                                  2024-07-18 00:00:00              None
89                                  2024-07-08 00:00:00              None
90                                  2024-07-08 00:00:00              None
91                                  2024-07-05 00:00:00              None
92                                  2024-07-04 00:00:00              None
93                                  2024-07-04 00:00:00              None
94                                  2024-07-04 00:00:00              None
95                                  2024-07-04 00:00:00              None
96                                  2024-07-04 00:00:00              None
97                                  2024-06-23 00:00:00              None
98                                  2024-06-07 00:00:00              None
99                                  2024-06-07 00:00:00              None
100                                 2024-06-07 00:00:00              None
101                                 2024-06-02 00:00:00              None
102                                 2024-06-02 00:00:00              None
103                                 2024-05-28 00:00:00              None
104                                 2024-05-24 00:00:00              None
105                                 2024-05-23 00:00:00              None
106                                 2024-05-02 00:00:00              None
107                                 2024-04-26 00:00:00              None
108                                 2024-04-26 00:00:00              None
109                                 2024-04-20 00:00:00              None
110                                 2024-04-20 00:00:00              None
111                                 2024-04-08 00:00:00              None
112                                         15 Mar 2024             March
113                                         04 Mar 2024             March
114                                         02 Mar-2024             March
115                                         25 Feb-2024          February
116                                         14 Feb-2024          February
117                                         04-Feb-2024          February
118                                         29 Jan-2024           January
119                                         15 Jan-2024           January
120                                         09-Jan-2024           January
121                                         05-Jan-2024           January
122                                         30 Dec-2023          December
123                                         29 Dec-2023          December
124                                         28 Dec-2023          December
125                                         25 Dec-2023          December
126                                         24-Dec-2023          December
127                                         18 Dec-2023          December
128                                        14  Dec-2023          December
129                                        14  Dec-2023          December
130                                         08 Dec-2023          December
131                                         04 Dec-2023          December
132                                         02 Dec-2023          December
133                                         30 Nov-2023          November
134                                         21 Nov-2023          November
135                                         10 Nov-2023          November
136                                         05 Nov-2023          November
137                                         03 Nov-2023          November
138                                         02 Nov-2023          November
139                                Reported 02 Nov-2023          November
140                                         31 Oct-2023           October
141                                         25 Oct 2023           October
142                                         23 Oct-2023           October
143                                         21 Oct-2023           October
144                                         20 Oct 2023           October
145                                         15 Oct 2023           October
146                                         13 Oct-2023           October
147                                         02 Oct-2023           October
148                                         01 Oct-2023           October
149                                         01 Oct-2023           October
150                                         18 Sep-2023         September
151                                         13 Sep-2023         September
152                                         12 Sep-2023         September
153                                         11 Sep-2023         September
154                                        09 Sep- 2023         September
155                                Reported 06-Sep-2023         September
156                                         04 Sep 2023         September
157                                         04 Sep 2023         September
158                                         25 Aug 2023            August
159                                         23 Aug-2023            August
160                                         22 Aug-2023            August
161                                         21 Aug-2023            August
162                                         16 Aug-2023            August
163                                         16 Aug-2023            August
164                                         12 Aug-2023            August
165                                         07 Aug-2023            August
166                                         31 Jul-2023              July
167                                         30 Jul-2023              July
168                                         29 Jul-2023              July
169                                         24 Jul-2023              July
170                                         22 Jul-2023              July
171                                         21 Jul-2023              July
172                                         18 Jul-2023              July
173                                         15 Jul-2023              July
174                                         14 Jul-2023              July
175                                Reported 14 Jul-2023              July
176                                         04 Jul-2023              July
177                                         04 Jul-2023              July
178                                         04 Jul-2023              July
179                                         04 Jul-2023              July
180                                         03 Jul-2023              July
181                                         03 Jul-2023              July
182                                         23-Jun-2023              June
183                                         23-Jun-2023              June
184                               Reported 14-June 2023              June
185                                         08-Jun 2023              June
186                                         07-Jun-2023              June
187                                         28-May 2023               May
188                                         28-May 2023               May
189                                         24-May 2023               May
190                                         24 May 2023               May
191                                 2023-05-20 00:00:00              None
192                                         21-May 2023               May
193                                        19 -May 2023               May
194                                         18-May-2023               May
195                                         14-May-2023               May
196                                         13-May-2023               May
197                                         11-May-2023               May
198                                         11-May-2023               May
199                                         09 May-2023               May
200                                         05-May-2023               May
201                                         03-May-2023               May
202                                         01-May-2023               May
203                                         29-Apr-2023             April
204                                         29-Apr-2023             April
205                                         23-Apr-2023             April
206                                         22-Apr-2023             April
207                                         11-Apr-2023             April
208                                         09-Apr-2023             April
209                                         09-Apr-2023             April
210                                         25-Mar-2023             March
211                                         25-Mar-2023             March
212                                         22-Mar-2023             March
213                                         19-Mar-2023             March
214                                         17-Mar-2023             March
215                                         16-Mar-2023             March
216                                         06-Mar-2023             March
217                                         05-Mar-2023             March
218                                         02-Mar-2023             March
219                                         21-Feb-2023          February
220                                         19-Feb-2023          February
221                                         19-Feb-2023          February
222                                         18-Feb-2023          February
223                                         17-Feb-2023          February
224                                         04-Feb-2023          February
225                                         30-Jan-2023           January
226                                        29 Jan--2023           January
227                                        08-Jan--2023           January
228                                         05-Jan-2023           January
229                                         01-Jan-2023           January
230                                            Jan-2023           January
231                                         30-Dec-2022          December
232                                         13-Dec-2022          December
233                                         11 Dec-2022          December
234                                         09-Dec-2022          December
235                                         08-Dec-2022          December
236                                         07-Dec-2022          December
237                                         27-Nov-2022          November
238                                         04-Nov-2022          November
239                                         03-Nov-2022          November
240                                         31-Oct-2022           October
241                                         28-Oct-2022           October
242                                         28-Oct-2022           October
243                                         27-Oct-2022           October
244                                         25 Oct-2022           October
245                                         23-Oct-2022           October
246                                         10-Oct-2022           October
247                                         08-Oct-2022           October
248                                         07-Oct-2022           October
249                                         06-Oct-2022           October
250                                         02-Oct-2022           October
251                                         25-Sep-2022         September
252                                         22-Sep-2022         September
253                                         06-Sep-2022         September
254                                         03-Sep-2022         September
255                                         31-Aug-2022            August
256                                         17-Aug-2022            August
257                                         15-Aug-2022            August
258                                         15-Aug-2022            August
259                                         15-Aug-2022            August
260                                         13-Aug-2022            August
261                                         10-Aug-2022            August
262                                         28-Jul-2022              July
263                                         27-Jul-2022              July
264                                         25-Jul-2022              July
265                                         20-Jul-2022              July
266                                         19-Jul-2022              July
267                                         19-Jul-2022              July
268                                         17-Jul-2022              July

In [371]:
#con dropna=False podemos ver que tenemos None y hay que eliminarlos
df['Month_full_strict'].value_counts(dropna=False)

Month_full_strict
July         775
August       667
None         637
September    608
January      568
June         547
October      502
December     493
April        491
November     457
March        456
May          447
February     416
Name: count, dtype: int64

In [372]:
#.notna() es un metodo que sirve para detectar los valores que no son nulos 
#el valor existe devuelve True, sino False
df = df[df['Month_full_strict'].notna()]

In [373]:
#Revisando que eliminamos los None
df['Month_full_strict'].value_counts(dropna=False)

Month_full_strict
July         775
August       667
September    608
January      568
June         547
October      502
December     493
April        491
November     457
March        456
May          447
February     416
Name: count, dtype: int64